print "[INFO] forms model init..."

# maps for question ui-code and full question content
global_ev_qs_map = {"ct-gr": "Group Randomization?", "ct-pgd": "Parallel Group Design?",
                    "ct-pk": "Study Focused on Pharmacokinetic Processes?",
                    "ct-ph": "Phenotyping?",
                    "ct-gt": "Genotyping?",
                    "cr-ae": "Reporting an adverse event?",
                    "cr-pr": "Publically reported?",
                    "cr-ep": "Icl an evaluation protocol?",
                    "exp-m-st": "Subtype?",
                    "exp-m-at": "Assay Type?",
                    "exp-m-mi": "Metabolic Inhibitor?",
                    "exp-t-st": "Subtype?",
                    "exp-t-at": "Assay Type?",
                    "exp-t-tp": "Transporter Protein?"}

global_ic_qs_map = {"cr-ic-question-1": "Previous Credible Reports in Humans?",
                    "cr-ic-question-2": "Interaction Consistent with Known Interactive Qualities of the Precipitant Drug?",
                    "cr-ic-question-3": "Interaction Consistent with Known Interactive Qualities of the Object Drug?",
                    "cr-ic-question-4": "Interaction Consistent with Known Reasonable Time Course of the Interaction (onset and/or offest)?",
                    "cr-ic-question-5": "Did the interaction remit upon de-challenge of the precipitant drug with no change in oject drug? (If no de-challenge, use unknown and skip to question 6)?",
                    "cr-ic-question-6": "Did the interaction reappear when precipitant drug was readministered with continued used of object drug?",
                    "cr-ic-question-7": "Reasonable alernative causes?",
                    "cr-ic-question-8": "Was the object drug detected in the blood or other fluids in concentrations consistent with the interaction?",
                    "cr-ic-question-9": "Was the drug interaction confirmed by objective evidence consistent with the affects on the object drug (other than from question 8)?",
                    "cr-ic-question-10": "Was the interaction greater when the precipitant dose was increased or less when the precipitant dose was decreased?",
                    "ct-ic-question-1": "Was there a polymorphic assertion linked as an assumption for the intended use of the evidence item?",
                    "ct-ic-question-2": "Was the specific genotype of the enzyme  noted in the description of evidence?",
                    "ct-ic-question-3": "If the substrate is being evaluated to support or refute that drug is a substrate of P-Glycoprotein, did the study compare wild type to variants in ABCB1 including 3435C$>$T, 2677G$>$T and 1236C$>$T?",
                    "ct-ic-question-4": "If the substrate is being evaluated to support or refute that drug is a substrate of OATP1B1, did the study compare wild type to variants in SLCO1B1?",
                    "ct-ic-question-5": "If the substrate is being evaluated to support of refute that a drug is a substrate of OATP1B3, did the study compare wild type to variants in SLCO1B3?",
                    "ex-mt-ic-question-1": "Enzyme Source:",
                    "ex-mt-ic-question-2": "NADPH Regenerating System:",
                    "ex-mt-ic-question-3": "Antibody Inhibitors:",
                    "ex-mt-ic-question-4": "In Vitro Selective Inhibitors:",
                    "ex-tp-ic-question-1": "Animal Study:",
                    "ex-tp-ic-question-2": "In Vitro Inhibitor:",
                    "ex-tp-ic-question-3": "Cell Line for P-Glycoprotein:",
                    "ex-tp-ic-question-4": "Appropriate Controls:"}
